Pandas permet de representer des donnees dans des DataFrames

In [ ]:
import pandas as pd

donnees = {
    "equipement": ["Routeur A", "Routeur B", "Switch C", "Serveur D"],
    "ville": ["Cotonou", "Bohicon", "Parakou", "Porto-Novo"],
    "temperature": [47, 68, 41, 75],
    "latence": [20, 80, 25, 95]
}


df = pd.DataFrame(donnees)

display(df)

print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.describe())
print(df.info())

  equipement       ville  temperature  latence
0  Routeur A     Cotonou           47       20
1  Routeur B     Bohicon           68       80
2   Switch C     Parakou           41       25
3  Serveur D  Porto-Novo           75       95

(4, 4)
Index(['equipement', 'ville', 'temperature', 'latence'], dtype='str')
equipement       str
ville            str
temperature    int64
latence        int64
dtype: object
       temperature    latence
count     4.000000   4.000000
mean     57.750000  55.000000
std      16.317169  38.078866
min      41.000000  20.000000
25%      45.500000  23.750000
50%      57.500000  52.500000
75%      69.750000  83.750000
max      75.000000  95.000000

In [21]:
import pandas as pd

donnees = {
    "equipement": ["Routeur A", "Routeur B", "Switch C", "Serveur D"],
    "ville": ["Cotonou", "Bohicon", "Parakou", "Porto-Novo"],
    "temperature": [47, 68, 41, 75],
    "latence": [20, 80, 25, 95]
}


df = pd.DataFrame(donnees)

print(df[["equipement","temperature"]])
print()
print(df[df["temperature"] > 65])
print()
print(df["latence"].mean())
print()
print(df[(df["temperature"] > 65) & (df["latence"] > 50)])

df["alertes"] = df["temperature"] > 65

display(df)

  equipement  temperature
0  Routeur A           47
1  Routeur B           68
2   Switch C           41
3  Serveur D           75

  equipement       ville  temperature  latence
1  Routeur B     Bohicon           68       80
3  Serveur D  Porto-Novo           75       95

55.0

  equipement       ville  temperature  latence
1  Routeur B     Bohicon           68       80
3  Serveur D  Porto-Novo           75       95

  equipement       ville  temperature  latence  alertes
0  Routeur A     Cotonou           47       20    False
1  Routeur B     Bohicon           68       80     True
2   Switch C     Parakou           41       25    False
3  Serveur D  Porto-Novo           75       95     True

loc sélectionne les données par étiquette de ligne et nom de colonne :
iloc sélectionne les données par position numérique (cest a dire par index)